### ISSUE TITLE
Can't add revenue

### ISSUE THREAD

**Issue by ikocevski** [brarcher/budget-watch#109]
I added a value in revenue tab and when I went to the budgets menu I saw -200 so, the revenue was actually added as an expense? I tried to edit that 200 in the revenue tab and the app crashed (crashes only if I press and hold on it and then tapping on edit, tapping once on it and opening the edit menu via the pencil icon works, this seems unrelated). Upon several attempts of editing it the edit menu opened but it indicated that this value was indeed an expense. So, the 200 stayed in the revenue tab but was actually considered as an expense, thus the title of the issue.

Update: I'm dumb, adding an expense puts +value because I'm going towards the indicated budget. I just got confused by this because of using many regular finance management apps. Sorry! 😁

**Comment by brarcher** [comment]
Sorry that the convention used in the app was not intuitive and caused confusion. It sounds like that is now resolved. However, I'm curious about the crash that you observed. Would you be able to reproduce this and capture logs? If you are able to do so, please open a new issue so the crash can be investigated. Thanks!
