### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by wbrawner** [brarcher/budget-watch#141]
Hey, I love the app, thanks!

I'd also love to contribute, but don't see any guidelines on doing so. Are you open to outside help? If so, how do you prefer code submissions?

Cheers

**Comment by brarcher** [comment]
Yes, I am open to outside help! Sorry I do not have a Contributing document, I'll add one. Generally the best way to propose a change is to fork the repo on GitHub then submit a pull request.

**Comment by wbrawner** [comment]
Cool! I assumed that, just wanted to be sure :)

**Comment by brarcher** [comment]
I've added a CONTRIBUTING.md file to the repo. Take a look and let me know if there are any questions.

**Comment by wbrawner** [comment]
Looks good, thanks!
