### ISSUE TITLE
The App fails to load the exported file

### ISSUE THREAD

**Issue by fabianmani** [brarcher/budget-watch#154]
I expected I'll be able to import successfully my successfully exported budget file. 

#### Actual behavior
The app shows import failed when I try to import the exported budget created by the app

#### How to reproduce
* Download and open the app. 
* click on + to add a budget
*  click the arrow sign on the top right corner of the screen
* export the budget, scroll down and try importing the exported data 

* Device: Tecno K7
* Operating system: Android 7.0
* App Version: 0.12

#### Recording Of The Bug
https://youtu.be/-PvHZr7_T54

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/the-app-fails-to-load-the-exported-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by brarcher** [comment]
From the video it appears you are using app version v0.21. Are you sure you are using v0.12?

The video glitches right before you click on import. Did you click on the "Use Export Location" button at the bottom?
Can you provide logs from when this happens? That will tell me the "why" of the failure. I'm not able to reproduce

**Comment by brarcher** [comment]
There are two ways you can try:

1) Create a bug report after reproducing the issue. Note that this will contain additional information about your device, so only attach it if you are comfortable about that.
https://developer.android.com/studio/debug/bug-report.html

2) Install the Android SDK and use "adb logcat" to capture the logs after reproducing the issue.
https://support.apteligent.com/articles/knowledge_base/How-to-Collect-Logs-via-Command-Line-ADB-on-Android-Devices

**Comment by brarcher** [comment]
If you are able to reproduce this and provide logs, then please re-open. I've not been able to reproduce this on my side, and will not be able to continue the investigation without additional information.
