### ISSUE TITLE
What is date format in CSV? (not a bug)

### ISSUE THREAD

**Issue by MarioMey** [brarcher/budget-watch#155]
I want to use exported data. Date values are, for example: 
1522551600000 (correspond to 2018/04/01)
1522119600000 (correspond to 2018/03/27)
What is this format? I don't understand. I check https://www.cl.cam.ac.uk/~mgk25/iso-time.html, expecting understanding... but no.

**Comment by brarcher** [comment]
The time field is the number of milliseconds since epoch. See https://github.com/brarcher/budget-watch/issues/144 for details.

**Comment by brarcher** [comment]
You can use the [epoch converter](https://www.epochconverter.com/) to decode the dates. For example:

1522551600000 => GMT: Sunday, April 1, 2018 3:00:00 AM
1522119600000 => GMT: Tuesday, March 27, 2018 3:00:00 AM
