### ISSUE TITLE
WebView disappear after device rotation

### ISSUE THREAD

**Issue by calbee633810** [brarcher/budget-watch#159]
Open About dialog and rotate screen, WebView disappears. Even though it's may not be a bug, the app can be more professional and user experience can be improved if WebView persist after screen orientation change.

![bug0-before](https://user-images.githubusercontent.com/38213896/38621085-adf3909c-3dd2-11e8-90c1-413c3ec67465.png)
Screenshot before orientation change

![bug0-after](https://user-images.githubusercontent.com/38213896/38621096-b616e38c-3dd2-11e8-8f7b-eccb36ac4e8d.png)
Screenshot after device rotation

Tested on Android 23 with Nexus 4 emulator

**Comment by brarcher** [comment]
This should be resolved now, and the fix will appear in the next release. Thanks for reporting it.
