### ISSUE TITLE
unnecessary check

### ISSUE THREAD

**Issue by armatus** [brarcher/budget-watch#16]
please remove the requiring of annotation in expenses

I'm already set up proper budget groups like 'beer' 'bike' etc.... I way to enter only amount of money and date when I enter my expenses.

it takes a lot of time to enter every annotation (top line)

**Comment by brarcher** [comment]
Oh, I did not think of that use case. Typically I would put the store name in the description field.

Sure, that requirement can be removed. Note, though, that when the transaction summary is brought up that the large part of it will be blank, as it is for displaying the store name. If this is OK, I can remove the requirement.

**Comment by armatus** [comment]
Dankon al vi!

it's ok. most used mode still budget lines for me.
I'm hardly use this app so i think to make a small request for usability
next time ))).
still thinking about how to make entering expenses better...

Regards

**Comment by brarcher** [comment]
> still thinking about how to make entering expenses better

I'll admit that the main use case which is implemented is the use case I was expecting to use. If you have or come up with ideas on how to improve it, let me know! (:

**Comment by brarcher** [comment]
Closing this issue for now.

@armatus if you feel otherwise, reopen it please. Otherwise, if you come up with some other usability improvements, let me know.

**Comment by armatus** [comment]
ok. close it. 0.3 will come with this feature?

**Comment by brarcher** [comment]
I think we have had a miscommunication.

A fix for this is now committed. The next release will make the description field optional.
