### ISSUE TITLE
Cannot rename budgets

### ISSUE THREAD

**Issue by monojp** [brarcher/budget-watch#164]
Hi,

I had a typo in one of my budgets and tried to rename it from "Mittagesen" to "Mittagessen". It can be renamed by long tapping and selecting "Edit", but the changes are not persisted and after editing the old name is displayed again.

Thanks and Regards
Martin

**Comment by brarcher** [comment]
This is in part an issue with how the database is setup. The budget name is used as the key, so renaming the budget would not work the way you would think. https://github.com/brarcher/budget-watch/issues/61 describes a fix, but no work has been done on it to date. Separately, attempting to change the budget also is broken, captured in https://github.com/brarcher/budget-watch/issues/156.

Marking this as a duplicate.
