### ISSUE TITLE
Importing from MyExpenses .csv file failed

### ISSUE THREAD

**Issue by takiainen** [brarcher/budget-watch#166]
Not sure if .CSV is some form of standard, but importing a .csv file created by another budget management app (MyExpenses) fails.

Would be nice to move over to completely free budget app, but I don't want throw away more than a year worth of data.

**Comment by brarcher** [comment]
CSV, or comma separated values, is a standard, but is very simple. It is like a spreadsheet as a plain text file where columns are separated by a comma and rows by a new line. That is about it.

On top of CSV, Budget Watch organizes data in a certain way. It is made up, so it is not likely the output of another app will cleanly import.

If you want you can take your CSV file, import it into your favorite spreadsheet program (like libre office), do some copy pasting to get the layout like Budget Watch expects, and export it to CSV and import it to Budget Watch. I cannot say what data your old app keeps, so I cannot say if all the data fields can be imported, but hopefully enough will work so it is useful.

You can create a few example budgets and transactions then export them to CSV to see what the Budget Watch format looks like.

If you go this route and have questions, let me know and I can try to help.

**Comment by brarcher** [comment]
I've not heard any reply back. If you want additional assistance please re-open.
