### ISSUE TITLE
Adding of image leads to crash.

### ISSUE THREAD

**Issue by Sammaz2** [brarcher/budget-watch#167]
### Actual behavior
When I opened the bugdet watch opensource android app. After that when I clicked on budgets option and then I clicked on plus sign to add budget. After that I filled the blanks and then saved it. Then I clicked on the that saved bugdet. After that i clicked on the plus sign to add an expense.  I filled the given details. After that I clicked on capture and then clicked on picsart to add an image. When I captured an image. And it clicked the arrow to add the image. Suddenly the app crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it. Open the app.

* Click on budgets option.

* And then click on the plus icon to add a budget. After that fill the given details. And save it.

* Then click on the saved budget.

* After that click on the plus icon to add expense. Then fill the given details.

* And click on the capture to add an image. After that click on the picsart instead of camera. And then take a picture and try to load it by clicking on the arrow. Unfortunately the app will crash.

https://youtu.be/E3lmxMMjMJ4 

* Browser: Bugdet watch

* Version:0.21.1

* Operating system:7.1.2

* Device model:Redmi 4

**Comment by brarcher** [comment]
I attempted to reproduce this myself on a simulator, but did not observe the crash. The video was unfortunately taken down already, so I could not see it.

Are you able to get me the logcat logs when the crash occurs, so I can get a stack trace?

**Comment by brarcher** [comment]
If this happens again and more information is available, please re-open. With the information provided I am not able to investigate further.
