### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by paulle** [brarcher/budget-watch#17]
Translations to other languages. Can help with Herman.

**Comment by brarcher** [comment]
If you are interested in translating Budget Watch into another language, your help would be appreciated! Kindly submit a pull request, and it can be included into the project.

**Comment by paulle** [comment]
Don't know ho to a pull request, but i translated the string into German:

**Comment by paulle** [comment]
<resources>
    <string name="app_name">Budget Watch</string>
    <string name="icon">icon</string>
    <string name="budgetsTitle">Budgets</string>
    <string name="addBudgetTitle">Budget hinzufügen</string>
    <string name="viewBudgetTitle">Budget ansehen</string>
    <string name="editBudgetTitle">Budget bearbeiten</string>
    <string name="budgetDescription">Budgets erstellen und verwalten</string>
    <string name="transactionsTitle">Transaktionen</string>
    <string name="transactionsDescription">Transaktionen und Einnahmen</string>
    <string name="addExpenseTransactionTitle">Ausgabe hinzufügen</string>
    <string name="editExpenseTransactionTitle">Ausgabe bearbeiten</string>
    <string name="viewExpenseTransactionTitle">Ausgabe ansehen</string>
    <string name="addRevenueTransactionTitle">Einnahme hinzufügen</string>
    <string name="editRevenueTransactionTitle">Einnahme bearbeiten</string>
    <string name="viewRevenueTransactionTitle">Einnahme ansehen</string>
    <string name="importExportTitle">Import/Export</string>

    <string name="add">Hinzufügen</string>
    <string name="selectDates">Daten auswählen</string>
    <string name="type">Typ</string>
    <string name="value">Wert</string>
    <string name="name">Name</string>
    <string name="budget">Budget</string>
    <string name="account">Konto</string>
    <string name="note">Notiz</string>
    <string name="date">Datum</string>
    <string name="save">Speichern</string>
    <string name="cancel">Abbrechen</string>
    <string name="set">Einrichten</string>
    <string name="receipt">Quittung</string>
    <string name="capture">Erfassung</string>
    <string name="view">Ansicht</string>
    <string name="update">Update</string>
    <string name="clean">Löschen</string>

    <string name="Grocery">Lebensmittel</string>
    <string name="one_hundred">100</string>
    <string name="fraction">%1$d/%2$d</string>

    <string name="budgetTypeMissing">Budgettyp ist leer</string>
    <string name="budgetValueMissing">Budgetwert ist leer</string>

    <string name="expensesTitle">Einnahmen</string>
    <string name="revenuesTitle">Ausgaben</string>

    <string name="edit">Bearbeiten</string>
    <string name="delete">Löschen</string>

    
    <string name="dateRangeFormat">%1$s ~ %2$s</string>

    <string name="noBudgets">Sie haben derzeit keine Budgets. Drücken Sie den "+" (plus) Knopf um anzufangen.\n\nBudget Watch lässt Sie Budgets erstellen und dann die monatlichen Ausgaben verfolgen.</string>
    <string name="noExpenses">Sie haben derzeit keine Ausgabentransaktionen. Drücken Sie den "+" (plus) Knopf um anzufangen.</string>
    <string name="noRevenues">Sie haben derzeit keine Einnahmentransaktionen. Drücken Sie den "+" (plus) Knopf um anzufangen.</string>

    <string name="budgetDateRangeHelp">Select date range to display for budgets</string>
    <string name="startDate">Start Datum</string>
    <string name="endDate">Ende Datum</string>
    <string name="startDateAfterEndDate">Startdatum muß gleich oder vor dem Enddatum sein</string>

    <string name="cleanupHelp">Datum wählen; alle Quittungen dieses oder vorheriger Daten werden gelöscht</string>

    <string name="importExport">Import/Export</string>
    <string name="importName">Import</string>
    <string name="exportName">Export</string>
    <string name="importExportHelp">Daten werden importiert nach/exportiert von BudgetWatch.csv im externen Speicher</string>
    <string name="importedFrom">Importiert von: %1$s</string>
    <string name="exportedTo">Exportiert nach: %1$s</string>
    <string name="fileMissing">Datei fehlt: %1$s</string>
    <string name="importFailed">Import fehlgeschlagen: %1$s</string>
    <string name="exportFailed">Export fehlgeschlagen: %1$s</string>
    <string name="importing">Importiere&#8230;</string>
    <string name="exporting">Exportiere&#8230;</string>

    <string name="purgeOldReceipts">Lösche alte Quittungen</string>
    <string name="cleaning">Lösche&#8230;</string>

    <string name="loading">Lade&#8230;</string>

    <string name="pictureCaptureError">Bild konnte nicht mit der Kamera aufgenommen werden</string>

    <string name="iconDescription">BudgetWatch icon</string>
    <string name="addExpenseDescription">Eine Ausgabentransaktion hinzufügen</string>
</resources>

    Status API Training Shop Blog About Pricing

**Comment by paulle** [comment]
[string-budget-german.txt](https://github.com/brarcher/budget-watch/files/138844/string-budget-german.txt)

**Comment by brarcher** [comment]
Thanks for contributing the German translations. They are included in the following pull requests:
https://github.com/brarcher/budget-watch/pull/20
https://github.com/brarcher/budget-watch/pull/18

The translations will appear in the next release.
