### ISSUE TITLE
Error displaying Spanish text

### ISSUE THREAD

**Issue by lupa18** [brarcher/budget-watch#175]
Spanish special symbols, like áéíóú appear changed with ?

see screenshot:
![screenshot_20180713-211510](https://user-images.githubusercontent.com/463429/42720281-47ac6f84-86f2-11e8-83e7-50f58c8a30f6.png)

**Comment by brarcher** [comment]
Hm. That string in the [resources file](https://github.com/brarcher/budget-watch/blob/master/app/src/main/res/values-es/strings.xml#L66) appears as:
```No tiene ningún presupuesto en este momento ... ```
which looks right. Maybe it is not encoded the way Android expects.

Do you notice that the application has always been this way, or only recently starting having this issue?

**Comment by lupa18** [comment]
Hello, 
Is the fist time I install this app and is the only app that have this problem

**Comment by brarcher** [comment]
Looking at the history of the Spanish translations file, it has only had one commit, that from its contributor in https://github.com/brarcher/budget-watch/pull/150.

@clinchergt, have you seen the issue with the Spanish translations as well? If so, do you recall specifically not seeing it from before (e.g. it was working before)?

**Comment by clinchergt** [comment]
Well, this is embarrassing. Just before I made the commit I made some quick modifications and probably didn't save it as UTF8.

**Comment by brarcher** [comment]
Yep, I think that is the case. The file is ISO-8859 encoding, whereas the other resources files are UTF-8. Thanks for posting a fix.

**Comment by brarcher** [comment]
Oh, FYI. The translations for the project are now handled in [Transifex](https://www.transifex.com/na-243/budget-watch), and I pull from there before release. I'll upload the updated file there, so that if in the future new strings are added the translations can be more easily added.

**Comment by brarcher** [comment]
Thanks for reporting the problem. I've created a new release with the fixed Spanish translations. Let me know if you encounter any other issues.
