### ISSUE TITLE
Crash when trying to add receipt

### ISSUE THREAD

**Issue by irfanns** [brarcher/budget-watch#23]
On One Plus One 6.0.1

Other than that, it's perfect. Thank you for the app!

**Comment by brarcher** [comment]
Glad that the app is useful!

Would you mind sending logs of the crash, so I can see what is going on? If you are using Android 6, can you check if the app currently has the permission to take a picture, and if setting the permission prevents the crash? The app currently does not dynamically request permissions.

**Comment by irfanns** [comment]
Hello, sorry to be late.
Yes, enabling permissions fixed that, though I have no idea if it's only the camera permission or if the storage permission is needed to.

Do you still want the crash logs? No idea how to generate those though.
Thanks for the help!

**Comment by brarcher** [comment]
The logs will not be necessary, as I think I understand the issue. When I update my phone to Android 6 I'll look into resolving this.

**Comment by brarcher** [comment]
I've created v0.3 of Budget Watch. When this change makes it to F-Droid in a few days and you choose to update, kindly let me know if it resolves the issue.

**Comment by irfanns** [comment]
Thanks. I'll be sure to do it.

**Comment by brarcher** [comment]
This issue should not be resolved. If it is not, please reopen the issue.
