### ISSUE TITLE
[Feature] Add total budget

### ISSUE THREAD

**Issue by strk** [brarcher/budget-watch#33]
At the moment there's no indication of what's the total budget value (sum of all budget values) so it is not easy to verify the subdivision is consistent with the expected overall amount.

**Comment by brarcher** [comment]
This feature has been added, and should appear in the next release. The Total field will look like the following on the Budget screen:

![screenshot_2016-07-12-23-47-53](https://cloud.githubusercontent.com/assets/5264535/16806592/11845ec0-48e3-11e6-9279-00479ade0f0a.png)
