### ISSUE TITLE
Please provide build instructions

### ISSUE THREAD

**Issue by strk** [brarcher/budget-watch#35]
There are no instructions to build the application, they would help users to become contributors :)

Incidentally I tried just running `gradle` but the build failed, should I file a ticket, considering I just made a wild guess about that being the way to build the code ?

**Comment by brarcher** [comment]
Running `gradle` failed? That should have resulted in the help task running, giving information about what one can do:
```
$ gradle
:help

Welcome to Gradle 2.12.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL
```

I'll commit some wrapper scripts for gradle. The scripts will download a compatible version of gradle, install it to the home directory, and invoke gradle. After, the README.md file will be updated with build instructions.

**Comment by brarcher** [comment]
Can you see if the build instructions in the README.md will be sufficient?

**Comment by strk** [comment]
Yes, thanks. I can build now (my system-installed gradle is 1.4, for the record).
